#+Title: Unidad 01 - Introducción y Virtualización
#+Author: Angel Berlanas Vicente

#+LATEX_HEADER: \hypersetup{colorlinks=true,urlcolor=blue}

#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \fancyhead{} % clear all header fields
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \fancyhead[R]{1-SMX}
#+LATEX_HEADER: \fancyhead[L]{Unidad 01: Sistemas Operativos]}

#+LATEX_HEADER:\usepackage{wallpaper}
#+LATEX_HEADER: \ULCornerWallPaper{0.9}{../rsrc/logos/header_europa.png}
#+LATEX_HEADER: \CenterWallPaper{0.7}{../rsrc/logos/watermark_1.png}

* Virtualización

  La virtualización es la tecnlogía que nos permite trabajar con el /Hardware/
  como si fuera /Software/. 
  
  Vamos a ver esto con un pequeño ejemplo.

  Cuando el programa que ejecutamos en un ordenador es relativamente simple, muchas
  veces consiste en un único archivo ejecutable que cuando se lanza, realiza la función
  que debe hacer y luego termina. Si deseamos actualizarlo, desinstalarlo, copiarlo, o 
  lo que se necesite, es sencillo: /basta con trabajar con el fichero/.
  
  Sin embargo, incluso en los programas más simples, existen una serie de /dependencias/, que 
  tienen que ver con los diferentes Sistemas Operativos, las versiones de las librerias gráficas, 
  las de acceso a disco, la gestión de los USB, etc. 

  A medida que los programas van complicándose y haciéndose más y más complejos comienzan a tener
  subsistemas y ficheros que son cargados dinámicamente para realizar determindas tareas (=.dll=).

  Otros ficheros que son utilizados por parte del Software en ejecución son:
  
  - Ficheros de datos.
  - Ficheros de configuración.
  - Imágenes: iconos, colores, etc.
  - ...

  Al final la instalación de un Software medio incluye una serie de ficheros ejecutables, librerias, 
  recursos y configuraciones que deben ser /copiados/ al Sistema Operativo destino para que se pueda
  ejecutar.

  El proceso no es sencillo y muchas veces no es posible realizar una /vuelta al estado inicial/.
  
  Si para el Software es complicado, para los Sistemas Operativos, que son piezas de Software que acaban
  muy vinculadas al Hardware, la instalación, desinstalación y configuración es al menos igual de complicada,
  /si no lo és mucho más/.
  
  Para los Administradores de Sistemas (/aka./ vosotros :-), la realización de pruebas de instalación
  es algo que haréis muy habitualmente.

  
* Tarea 06 [ CLIL ] : Why is Virtualization Useful?

  Lee el texto que aparece a continuación y contexta a las preguntas:
  
  El texto ha sido extraido del Manual de VirtualBox:
  [[https://www.virtualbox.org/manual/ch01.html#virt-why-useful]]

  

\newpage
  ---
  The techniques and features that Oracle VM VirtualBox provides are useful
  in the following scenarios:

   + *Running multiple operating systems simultaneously*
       Oracle VM VirtualBox enables you to run more than one OS at a time. This way, you can run software written for one OS on another, such as Windows software on Linux or a Mac, without having to reboot to use it. Since you can configure what kinds of virtual hardware should be presented to each such OS, you can install an old OS such as DOS or OS/2 even if your real computer's hardware is no longer supported by that OS.
   + *Easier software installations* 
       Software vendors can use virtual machines to ship entire software configurations. For example, installing a complete mail server solution on a real machine can be a tedious task. With Oracle VM VirtualBox, such a complex setup, often called an appliance, can be packed into a virtual machine. Installing and running a mail server becomes as easy as importing such an appliance into Oracle VM VirtualBox.
   + *Testing and disaster recovery* 
       Once installed, a virtual machine and its virtual hard disks can be considered a container that can be arbitrarily frozen, woken up, copied, backed up, and transported between hosts.
       On top of that, with the use of another Oracle VM VirtualBox feature called snapshots, one can save a particular state of a virtual machine and revert back to that state, if necessary. This way, one can freely experiment with a computing environment. If something goes wrong, such as problems after installing software or infecting the guest with a virus, you can easily switch back to a previous snapshot and avoid the need of frequent backups and restores.
       Any number of snapshots can be created, allowing you to travel back and forward in virtual machine time. You can delete snapshots while a VM is running to reclaim disk space.
   + *Infrastructure consolidation*
       Virtualization can significantly reduce hardware and electricity costs. Most of the time, computers today only use a fraction of their potential power and run with low average system loads. A lot of hardware resources as well as electricity is thereby wasted. So, instead of running many such physical computers that are only partially used, one can pack many virtual machines onto a few powerful hosts and balance the loads between them. 
  ---
\newpage

  1. Realiza un listado de las palabras que no conoces su significado.
  2. ¿Qué significa la expresión : /ship entire software configurations/.?
  3. Explica la frase: /a virtual machine and its virtual hard disks can be considered a container that can be arbitrarily frozen, woken up, copied, backed up, and transported between hosts/.
  4. ¿Qué nos aportan los /snapshots/?.¿Qué recursos del /anfitrión/ utilizan?
  5. En el último punto (/Infraestructure consolidation/), explica en castellano porqué
     las Herramientas de Virtualización pueden reducir el uso de los recursos energéticos.
  
     
